Block commits directly to main

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -6,6 +6,11 @@
 
 cd "$(git rev-parse --show-toplevel)" || exit 1
 
+if [ "$(git branch --show-current)" = 'main' ]; then
+    printf 'ERROR! Committing directly to main!\n' >&2
+    exit 1
+fi
+
 # ensure that the version file is not associated with an existing version
 if [ "$(git tag --list "v$(cat version)" | wc -c)" -gt 0 ]; then
     printf 'ERROR! Version file corresponds to an existing tag!\n'
